language: ruby
rvm:
  - 2.1.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
env:
  global:
    - PG_USERNAME='postgres'
script:
  - "bundle exec rake db:create"
  - "bundle exec rake db:migrate RAILS_ENV=test"
  - "bundle exec rake spec"